// alert("hello world!");
// console.log(45+13);
alert("Hello World!");
console.log(45+34);
let country="India";
let personName="Pritam";
let continent='Europe';
let population=15;
console.log(country);
console.log(personName);
console.log(continent);
console.log(population);